extraction:
  cpp:
    prepare:
      packages:
        - openmpi-bin
        - libopenmpi-dev
        - libhdf5-openmpi-dev
        - libadios-dev  # this is OpenMPI-enabled, explicit name on disco+
