name: wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]  # windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'src'
        ref: '0.11.1-alpha'

    - uses: actions/checkout@v2
      with:
        path: 'src/.github/'

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Build wheel
      env:
        # (1,2) Skip building for Python 2.7 on all platforms
        # (3) CMake/Pybind11 scripts not clever enough to build 32bit Windows with 64bit compiler
        # (4) GNU 7.3.1 & MPark.Variant 1.4.0 on i686:
        #     https://github.com/pypa/manylinux/issues/543
        #       variant.hpp:2241:9: internal compiler error:
        #       unexpected expression ‘I’ of kind template_parm_index
        #       typename T = lib::type_pack_element_t<I, Ts...>,
        # (5) skip Windows until we add HDF5 and ADIOS2 build scripts
        CIBW_SKIP: cp27-* pp27-* *-win32 *-manylinux_i686 *win*
        # Install dependencies on Linux and OSX
        CIBW_BEFORE_BUILD: bash -x .github/library_builders.sh
        # CMake shall search for static dependencies of HDF5 and ADIOS1
        HDF5_USE_STATIC_LIBRARIES: ON
        ADIOS_USE_STATIC_LIBS: ON
      run: |
        cd src
        python -m cibuildwheel --output-dir ../wheelhouse

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
